### ISSUE TITLE
ios 13 example seems broken for swipe right. 

### ISSUE THREAD

**Issue by 8secz-johndpope** [artemnovichkov/TransitionRouter#1]

**Comment by artemnovichkov** [comment]
I haven't update TransitionRouter for long time. What do you mean? Black screen after dismissing?

**Comment by 8secz-johndpope** [comment]
yes - seems to be happening to every sample code.
I'm going to try this newer version
https://raw.githubusercontent.com/ccrama/Slide-iOS/dc77f57db0173e49a24f5c0a7987bead063b152e/Slide%20for%20Reddit/SwipeForwardNavigationController.swift
